from __future__ import annotations

import os
import re
from dataclasses import dataclass
from typing import Iterable


SECTION_HEADINGS = [
    "Summary",
    "Symptoms",
    "Impact",
    "Likely Root Cause",
    "Resolution Steps",
    "Commands Used",
    "Verification",
    "Prevention Checklist",
    "Escalation / Follow-up",
]

COMMAND_PREFIXES = (
    "kubectl ",
    "helm ",
    "docker ",
    "systemctl ",
    "journalctl ",
    "curl ",
    "dig ",
    "nslookup ",
    "ping ",
    "ssh ",
    "scp ",
    "rsync ",
    "sudo ",
    "ip ",
    "ss ",
    "netstat ",
    "openssl ",
    "mysql ",
    "psql ",
    "grep ",
    "cat ",
    "tail ",
    "df ",
    "du ",
)

SYMPTOM_WORDS = ("error", "failed", "failure", "down", "outage", "crash", "timeout", "refused", "unavailable", "502", "503", "404")
ROOT_CAUSE_WORDS = ("because", "root cause", "caused by", "refused", "misconfig", "expired", "missing", "crashloop", "oom", "disk")
RESOLUTION_WORDS = ("fixed", "resolved", "restart", "rolled", "applied", "patched", "scaled", "deleted", "recreated", "updated")
VERIFY_WORDS = ("verified", "confirm", "confirmed", "tested", "healthy", "200", "success", "passing")


@dataclass(frozen=True)
class RunbookInput:
    title: str
    system: str
    runbook_type: str
    tags: str
    raw_notes: str


def generate_runbook(title: str, system: str, runbook_type: str, tags: str, raw_notes: str) -> str:
    """Generate structured markdown using optional AI only when configured.

    The deterministic local generator is the supported fallback and is intentionally
    dependency-free so the MVP works without any secrets or network calls.
    """
    data = RunbookInput(
        title=_clean_inline(title) or "Untitled Runbook",
        system=_clean_inline(system) or "Unspecified system",
        runbook_type=_clean_inline(runbook_type) or "General Runbook",
        tags=_clean_inline(tags),
        raw_notes=(raw_notes or "").strip(),
    )

    if _ai_enabled():
        ai_markdown = _try_openai_compatible_generation(data)
        if ai_markdown:
            return ai_markdown

    return _deterministic_markdown(data)


def _deterministic_markdown(data: RunbookInput) -> str:
    lines = _meaningful_lines(data.raw_notes)
    commands = _extract_commands(lines)
    symptoms = _select_lines(lines, SYMPTOM_WORDS, fallback_count=3)
    root_causes = _select_lines(lines, ROOT_CAUSE_WORDS, fallback_count=2)
    resolutions = _select_lines(lines, RESOLUTION_WORDS, fallback_count=4)
    verifications = _select_lines(lines, VERIFY_WORDS, fallback_count=3)

    summary = _summary_sentence(data, lines)
    impact = _impact_sentence(data, symptoms)

    metadata = [
        f"- System / Client: {data.system}",
        f"- Runbook Type: {data.runbook_type}",
        f"- Tags: {data.tags or 'None supplied'}",
        "- Generated by: Runbook Forge AI deterministic local generator",
    ]

    parts = [
        f"# {data.title}",
        "",
        *metadata,
        "",
        "## Summary",
        summary,
        "",
        "## Symptoms",
        _bullet_list(symptoms, "Capture the externally visible symptom(s) here."),
        "",
        "## Impact",
        impact,
        "",
        "## Likely Root Cause",
        _bullet_list(root_causes, "TODO: Confirm the underlying cause from logs, metrics, or operator notes."),
        "",
        "## Resolution Steps",
        _numbered_list(resolutions, "Review the raw notes, identify the corrective action, and document the exact step."),
        "",
        "## Commands Used",
        _code_block_list(commands),
        "",
        "## Verification",
        _bullet_list(verifications, "TODO: Add a repeatable health check that proves the issue is resolved."),
        "",
        "## Prevention Checklist",
        "- [ ] Add or tune monitoring/alerting for the symptom above.",
        "- [ ] Document owner, escalation path, and expected response time.",
        "- [ ] Add backup/rollback notes if the fix changes state.",
        "- [ ] Schedule a follow-up review after the next maintenance window.",
        "",
        "## Escalation / Follow-up",
        "- Escalate if symptoms return after the documented resolution steps.",
        "- Follow up by replacing TODOs with validated environment-specific details.",
        "",
        "## Raw Notes Appendix",
        "```text",
        data.raw_notes or "No raw notes supplied.",
        "```",
        "",
    ]
    return "\n".join(parts)


def _meaningful_lines(raw_notes: str) -> list[str]:
    lines: list[str] = []
    for line in raw_notes.splitlines():
        cleaned = line.strip().strip("-•")
        if cleaned:
            lines.append(cleaned)
    if not lines and raw_notes.strip():
        lines = [raw_notes.strip()]
    return lines


def _extract_commands(lines: Iterable[str]) -> list[str]:
    commands: list[str] = []
    for line in lines:
        stripped = re.sub(r"^[$#>]\s*", "", line.strip())
        lower = stripped.lower()
        if lower.startswith(COMMAND_PREFIXES) or " kubectl " in f" {lower} ":
            commands.append(stripped)
    return _dedupe(commands)


def _select_lines(lines: list[str], keywords: tuple[str, ...], fallback_count: int) -> list[str]:
    selected = [line for line in lines if any(word in line.lower() for word in keywords)]
    if not selected:
        selected = lines[:fallback_count]
    return _dedupe(selected[: max(fallback_count, 1)])


def _summary_sentence(data: RunbookInput, lines: list[str]) -> str:
    if lines:
        first = lines[0].rstrip(".")
        return f"This {data.runbook_type.lower()} runbook for {data.system} documents: {first}."
    return f"This {data.runbook_type.lower()} runbook for {data.system} was generated from empty notes and needs operator detail."


def _impact_sentence(data: RunbookInput, symptoms: list[str]) -> str:
    if symptoms:
        return f"Impact is inferred from the reported symptoms for {data.system}: {symptoms[0]}"
    return f"TODO: Document user/business impact for {data.system}."


def _bullet_list(items: list[str], fallback: str) -> str:
    source = items or [fallback]
    return "\n".join(f"- {item}" for item in source)


def _numbered_list(items: list[str], fallback: str) -> str:
    source = items or [fallback]
    return "\n".join(f"{index}. {item}" for index, item in enumerate(source, start=1))


def _code_block_list(commands: list[str]) -> str:
    if not commands:
        return "```bash\n# TODO: Add commands used during investigation or remediation.\n```"
    return "\n\n".join(f"```bash\n{command}\n```" for command in commands)


def _dedupe(items: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        key = item.strip().lower()
        if key and key not in seen:
            seen.add(key)
            result.append(item.strip())
    return result


def _clean_inline(value: str | None) -> str:
    return re.sub(r"\s+", " ", (value or "").strip())


def _ai_enabled() -> bool:
    return bool(os.getenv("OPENAI_API_KEY") and os.getenv("OPENAI_BASE_URL"))


def _try_openai_compatible_generation(data: RunbookInput) -> str | None:
    """Placeholder hook for future AI generation.

    Secrets are intentionally never printed. The MVP keeps deterministic output as
    the dependable default. Returning None makes fallback behavior explicit.
    """
    return None
